---
- name: ES apt repo
  apt_repository:
    repo="deb http://packages.elastic.co/elasticsearch/{{ elk_elasticsearch.version }}/{{ ansible_os_family|lower }} stable main"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install ES apt packages
  apt: pkg=elasticsearch update_cache=yes force=yes state=latest
  sudo: yes
  when: ansible_os_family == 'Debian'
  notify: Restart elasticsearch

- name: Install PIP
  apt: pkg=python-pip force=yes state=latest
  sudo: yes

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch

# Example action to start service elasticsearch, if not running
- name: ensure elasticsearch service is up
  service: name=elasticsearch state=started
  sudo: yes
  
# wait 300 seconds for port 9200 to become open on the host, don't start checking for 10 seconds
- name: wait for elasticsearch port
  wait_for: port={{ elk_elasticsearch.http.port }} delay=10
