---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: WebUpd8 apt repo
  apt_repository:
    repo='ppa:webupd8team/java'
    update_cache=yes
  sudo: yes

- name: Check Oracle license
  shell:
    /usr/bin/debconf-show oracle-java8-installer |awk '/accepted-oracle-license/{print $NF}'
  sudo: yes
  changed_when: False
  register: webupd8team

- name: Accept Oracle license
  shell:
    echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | /usr/bin/debconf-set-selections
  sudo: yes

- name: Java apt packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items: "{{ elk_java_packages }}"
  sudo: yes
  
- name: Check java  Version
  command: java -version
  register: result
  ignore_errors: True
  
- name: Output java version
  debug: msg={{ result }}
